FROM centos:7.2.1511

RUN rpm --import https://archive.cloudera.com/cdh5/redhat/7/x86_64/cdh/RPM-GPG-KEY-cloudera && \
	yum clean all

RUN rpm -Uih https://archive.cloudera.com/cdh5/one-click-install/redhat/7/x86_64/cloudera-cdh-5-0.x86_64.rpm && \
	yum -y install \
		java-1.8.0-openjdk-devel \
		perl \
		sudo && \
	yum clean all

ENV CDH_VERSION=5.6.0

RUN perl -i -pe "s:/cdh/5/:/cdh/${CDH_VERSION}/:g" /etc/yum.repos.d/cloudera-cdh5.repo

RUN yum -y install \
		avro-tools \
		crunch \
		hadoop \
		hadoop-client \
		lzo && \
	yum clean all

RUN rm -rf /var/lib/hadoop-hdfs

COPY conf/* /etc/hadoop/conf/

COPY bin/hadoopclient/bootstrap /sbin/bootstrap

RUN chmod +x /sbin/bootstrap

RUN chown -R hdfs:hdfs /etc/hadoop

RUN mkdir -p /var/lib/hadoop-hdfs && chown -R hdfs:hdfs /var/lib/hadoop-hdfs

RUN cd /usr/local && \
	curl -SLO 'http://search.maven.org/remotecontent?filepath=org/apache/maven/apache-maven/3.3.9/apache-maven-3.3.9-bin.tar.gz' && \
	tar -xzvf apache-maven-3.3.9-bin.tar.gz && \
	rm -rfv apache-maven-3.3.9-bin.tar.gz && \
	echo 'export PATH=$PATH:/usr/local/apache-maven-3.3.9/bin' > /etc/profile.d/mvn_env.sh

RUN chmod 555 /etc/profile.d/mvn_env.sh

ENV JAVA_HOME=/usr/lib/jvm/java

RUN cd /usr/local && \
	curl -SLO 'https://github.com/apache/incubator-apex-core/archive/v3.3.0-incubating.tar.gz' && \
	tar -xzvf v3.3.0-incubating.tar.gz && \
	rm -rfv v3.3.0-incubating.tar.gz && \
	chown -R hdfs:hdfs /usr/local/apex-core-3.3.0-incubating
	
RUN echo 'export PATH=$PATH:/usr/local/apex-core-3.3.0-incubating/engine/src/main/scripts' > /etc/profile.d/apex_env.sh

RUN chmod 555 /etc/profile.d/apex_env.sh

USER hdfs

RUN cd /usr/local/apex-core-3.3.0-incubating && \
	export PATH=$PATH:/usr/local/apache-maven-3.3.9/bin && \
	mvn install
	
WORKDIR /tmp

CMD ["/sbin/bootstrap"]
