FROM centos:7.2.1511

RUN rpm --import https://archive.cloudera.com/cdh5/redhat/7/x86_64/cdh/RPM-GPG-KEY-cloudera && \
	yum clean all

RUN rpm -Uih https://archive.cloudera.com/cdh5/one-click-install/redhat/7/x86_64/cloudera-cdh-5-0.x86_64.rpm && \
	yum -y install \
		java-1.8.0-openjdk-devel \
		perl \
		sudo && \
	yum clean all

ENV CDH_VERSION=5.6.0

RUN perl -i -pe "s:/cdh/5/:/cdh/${CDH_VERSION}/:g" /etc/yum.repos.d/cloudera-cdh5.repo

RUN yum -y install \
		avro-tools \
		crunch \
		hadoop \
		hadoop-yarn-resourcemanager \
		lzo && \
	yum clean all

RUN rm -rf /var/lib/hadoop-hdfs

COPY conf/* /etc/hadoop/conf/

COPY bin/resourcemanager/bootstrap /sbin/bootstrap

RUN chmod +x /sbin/bootstrap

EXPOSE 8032 8030 8031 8033 8088 8090

CMD ["/sbin/bootstrap"]
